#!/usr/bin/env python3

import argparse

from pythonosc import osc_server

from Synapse import dispatcher


parser = argparse.ArgumentParser()
parser.add_argument("--ip",
                    default="10.1.1.181", help="The ip to listen on")
parser.add_argument("--port",
                    type=int, default=7002, help="The port to listen on")


if __name__ == "__main__":
    args = parser.parse_args()
    server = osc_server.ThreadingOSCUDPServer(
        (args.ip, args.port), dispatcher)
    print("Serving on {}".format(server.server_address))
    server.serve_forever()
