#!/usr/bin/env python3

import argparse
from pythonosc import osc_server
from Synapse import dispatcher
import netifaces as ni

ni.ifaddresses('eth0')

DEFAULT_IP = ni.ifaddresses('eth0')[ni.AF_INET][0]['addr']
DEFAULT_PORT = 7002

parser = argparse.ArgumentParser()
parser.add_argument("--ip",
                    default=DEFAULT_IP, help="The ip to listen on")
parser.add_argument("--port",
                    type=int, default=DEFAULT_PORT, help="The port to listen on")


if __name__ == "__main__":
    args = parser.parse_args()
    # server = osc_server.ThreadingOSCUDPServer(
    server = osc_server.ThreadingOSCUDPServer(
        (args.ip, args.port), dispatcher)
    print("Serving on {}".format(server.server_address))
    server.serve_forever()
